logging:
  file:
    path: /Volumes/files/IdeaProjects/SpringBoot/configuration-log/src/main/resources #\u6587\u4EF6\u540D\u4E3Aspring.log
    name: /Volumes/files/IdeaProjects/SpringBoot/configuration-log/src/main/resources/spring-logging-file-nametest  #\u540C\u65F6\u5B58\u5728name\u751F\u6548

  level:
    com.malu: trace
  pattern:
    file: "%d{yyyy-MM-dd}===%-5p===%thread===%class===%logger===%msg%n"

